import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import vm from 'node:vm';import crypto from 'node:crypto';
import {build} from '../../scripts/build-customer-names-r6.mjs';
const root=new URL('../../',import.meta.url),extension=fs.readFileSync(new URL('worker-patches/customer-names-r6.js',root),'utf8');
const id='11111111-1111-4111-8111-111111111111',id2='22222222-2222-4222-8222-222222222222';
function fixture({allowed=true,tasks=[{id,channelType:'chat',customer:{name:'Test Customer'},lastAgent:{name:'Not the customer'}}],status=200,body,hang=false,short=false}={}){
 let calls=0;const env={WEBEX_ORG_ID:'org-test',WEBEX_AUTH_KV:{get:async()=>({baseUrl:'https://test.example'})}};
 const c=vm.createContext({URL,Map,Set,AbortController,Date,JSON,Promise,Number,String,Response,clearTimeout,
  setTimeout:short?(fn,n)=>setTimeout(fn,Math.min(n,15)):setTimeout,WEBEX_REGION_STATE_KEY:'region',
  checkAccess:async()=>({allowed}),json:(x,h={},status=200)=>new Response(JSON.stringify(x),{status,headers:{...h,'Content-Type':'application/json'}}),
  webexFetch:async(_env,url,options)=>{calls++;assert.ok(url.startsWith('https://test.example/search?'));const q=JSON.parse(options.body).query;assert.ok(q.includes('customer {name}'));assert.ok(!/phoneNumber|email|transcript|lastAgent/.test(q));
   if(hang)return new Promise(()=>{});return new Response(JSON.stringify(body??{data:{taskDetails:{tasks,pageInfo:{hasNextPage:false,endCursor:null}}}}),{status,headers:{'Content-Type':'application/json'}});}});
 vm.runInContext(extension+'\nglobalThis.api={handleWebexCustomerNames,vbNameIds,vbNameValue,vbNameCache,vbNameQuery};',c);
 return {api:c.api,env,count:()=>calls,request:(ids=id)=>c.api.handleWebexCustomerNames(new Request('https://test.example/api/webex/chat-customer-names?ids='+encodeURIComponent(ids)),env,{'Access-Control-Allow-Origin':'https://dashboard.example'})};
}
test('denied access is checked before query or cache',async()=>{const f=fixture({allowed:false});assert.equal((await f.request()).status,403);assert.equal(f.count(),0);});
test('UUID validation blocks arbitrary filters and oversized input',async()=>{for(const value of ['bad','',id+',x',Array(51).fill(id).join(',')]){const f=fixture();assert.equal((await f.request(value)).status,400);assert.equal(f.count(),0);}});
test('name mapped by exact contact ID; not agent name or unrelated fields',async()=>{const f=fixture(),r=await f.request();assert.equal(r.status,200);const x=await r.json();assert.deepEqual(x.rows,[{contactId:id,customerName:'Test Customer',nameStatus:'reported'}]);assert.equal(x.identityVerified,false);assert.equal(r.headers.get('Cache-Control'),'no-store');});
test('no customer value is explicitly missing and not guessed',async()=>{const f=fixture({tasks:[{id,channelType:'chat',lastAgent:{name:'Agent'},customer:{email:'not-requested@example.test'}}]});assert.equal((await(await f.request()).json()).rows[0].customerName,null);});
test('one cached batch coalesces concurrent lookups',async()=>{const f=fixture();await Promise.all([f.request(),f.request()]);await f.request();assert.equal(f.count(),1);});
test('cache never crosses organization',async()=>{const f=fixture();await f.request();f.env.WEBEX_ORG_ID='other-org';await f.request();assert.equal(f.count(),2);});
test('malicious control characters removed without changing Unicode names',()=>{const f=fixture();assert.equal(f.api.vbNameValue(' Zoë O’Connor\u202e\n '),'Zoë O’Connor');assert.equal(f.api.vbNameValue('x'.repeat(161)),null);assert.equal(f.api.vbNameValue({}),null);});
test('wrong-contact, duplicate and wrong-channel rows fail closed',async()=>{for(const tasks of [[{id:id2,channelType:'chat'}],[{id,channelType:'telephony'}],[{id,channelType:'chat'},{id,channelType:'chat'}]]){const f=fixture({tasks});assert.equal((await f.request()).status,503);}});
test('HTTP, invalid JSON/schema and GraphQL errors stay optional failures',async()=>{for(const options of [{status:503},{body:{errors:[{message:'internal details'}]}},{body:{}},{body:{data:{taskDetails:{tasks:[]}}}}]){const f=fixture(options),r=await f.request(),s=await r.text();assert.equal(r.status,503);assert.ok(!s.includes('internal details'));}});
test('optional hung name query terminates; no change to core reporting',async()=>{const f=fixture({hang:true,short:true}),r=await f.request();assert.equal(r.status,503);assert.equal(f.count(),1);});
test('original Worker bytes and all old routes preserved exactly',{skip:!process.env.VB_PRIVATE_BASELINE},()=>{const source=fs.readFileSync(process.env.VB_PRIVATE_BASELINE,'utf8'),r=build(source,extension);assert.equal(r.proof.originalBytesPreserved,true);assert.ok(Object.values(r.proof.routes).every(n=>n===1));assert.equal(r.candidate.replace('if (path === "/api/webex/chat-customer-names" && method === "GET") {\n  return handleWebexCustomerNames(request, env, cors);\n}\n\n','').split('\n/* BEGIN OPTIONAL CUSTOMER NAMES R6 */')[0],source);});
test('arbitrary Worker source cannot build a deployable candidate',()=>assert.throws(()=>build('export default {}',extension)));
test('legacy distinguishes confirmed empty roster from errors',()=>{const s=fs.readFileSync(new URL('dashboard.js',root),'utf8');assert.ok(s.includes('if (!Array.isArray(data?.AgentStatus))'));assert.ok(s.includes('No agents are currently reported by the legacy service.'));assert.ok(s.includes('This does not mean all agents are signed out.'));assert.ok(!s.includes('!data.AgentStatus || data.AgentStatus.length === 0'));assert.ok(s.includes('30000'));});
test('customer feature does not add PII to core Chat queries',()=>{assert.ok(!extension.includes('VB_CHAT_TASK_FIELDS ='));assert.ok(!extension.includes('vbChatCollect ='));assert.ok(!extension.includes('scheduled('));});
test('frontend names use existing HTML escaping and CSV formula protection',()=>{const s=fs.readFileSync(new URL('webex-integrated-chat.js',root),'utf8');assert.ok(s.includes("['Customer Name',nameFor]"));assert.ok(s.includes("esc(c[1](r)??'Unavailable')"));assert.ok(s.includes('s="\'"+s'));assert.ok(s.includes('nextNameAttempt=Date.now()+60000'));assert.ok(s.includes('customerNames.clear();namesController?.abort()'));});

test('periodic update actually invokes optional name loading',()=>{const s=fs.readFileSync(new URL('webex-integrated-chat.js',root),'utf8');assert.ok(s.slice(s.indexOf('  function tick()')).includes('void requestCustomerNames();'));});
