import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import vm from 'node:vm';
const source=fs.readFileSync(new URL('../worker-patches/agent-queue-state-r3.js',import.meta.url),'utf8');
const ctx=vm.createContext({buildWebexAgentRows:()=>[],buildWebexQueueRows:()=>[],formatWebexDurationMs:n=>String(n)});vm.runInContext(source,ctx);
const now=1790351600000;
const slot=(id,state='available',more={})=>({channelId:id,channelType:'chat',currentState:state,lastActivityTime:now-1000,...more});
const summary=(slots,type='chat')=>ctx.vbOpsChannelSummary({agentId:'A',channelInfo:slots},type,now);
const queues=[{id:'Q',channelType:'TELEPHONY',calls:8},{id:'R',channelType:'TELEPHONY'}];
const task=(state='connected',more={})=>({id:'T',isActive:true,status:state,channelType:'telephony',lastQueue:{id:'Q'},lastActivityTime:now-1000,...more});
const leg=(state='parked',more={})=>({taskId:'T',isActive:true,contactState:state,channelType:'telephony',queue:{id:'Q'},lastActivityTime:now-2000,...more});
const run=(tasks=[],legs=[],agents=[])=>ctx.vbOpsCurrentQueueRows(queues,legs,tasks,agents,now);
const work=(bucket='wrapup',more={})=>({agentId:'A',currentInteractions:[{taskId:'T',queueId:'Q',channel:'telephony',bucket,at:now-1000,...more}]});
const five=()=>Array.from({length:5},(_,i)=>slot('c'+i));
test('Five available slots are valid, not ambiguous',()=>{const s=summary(five());assert.equal(s.routingState,'available');assert.equal(s.capacity,5);assert.equal(s.availableSlots,5);});
test('One active chat out of five is Engaged, four reported slots available',()=>{const s=summary([slot('c0','connected'),...five().slice(1)]);assert.equal(s.routingState,'engaged');assert.equal(s.activeSlots,1);assert.equal(s.availableSlots,4);});
test('Five concurrent chats counted without clamping to one',()=>assert.equal(summary(five().map(s=>({...s,currentState:'connected'}))).activeSlots,5));
test('Wrapup does not become waiting or active',()=>{const s=summary(five().map(s=>({...s,currentState:'wrapup'})));assert.equal(s.wrapupSlots,5);assert.equal(s.activeSlots,0);assert.equal(s.routingState,'wrapup');});
test('Available and engaged mixed slots retain engaged summary',()=>assert.equal(summary([slot('a'),slot('b','connected'),slot('c','wrapup')]).routingState,'engaged'));
test('Duplicate channel identity not counted twice',()=>assert.equal(summary([slot('c'),slot('c')]).capacity,1));
test('Conflicting duplicate slot does not fabricate Available',()=>assert.equal(summary([slot('c'),slot('c','idle')]).routingState,null));
test('Missing channel is unknown, not unavailable',()=>assert.equal(summary([]).routingState,null));
test('Newer duplicate slot wins',()=>assert.equal(summary([slot('c','idle'),slot('c','available',{lastActivityTime:now})]).routingState,'available'));
test('Explicit Idle reason retained',()=>assert.equal(summary([slot('c','idle',{idleCodeName:'Lunch'})]).idleReason,'Lunch'));
test('Overall available is same for both media',()=>assert.equal(ctx.vbOpsAgentStatus(summary([slot('v','available',{channelType:'telephony'})],'telephony'),summary(five()),now).state,'Available'));
test('Voice engaged plus five available chats: overall Engaged',()=>assert.equal(ctx.vbOpsAgentStatus(summary([slot('v','connected',{channelType:'telephony'})],'telephony'),summary(five()),now).state,'Engaged'));
test('Voice wrapup overrides otherwise available summary',()=>assert.equal(ctx.vbOpsAgentStatus(summary([slot('v','wrapup',{channelType:'telephony'})],'telephony'),summary(five()),now).state,'Wrap-up'));
test('Connected call is active, not waiting despite old parked leg',()=>{const q=run([task()], [leg()])[0];assert.equal(q.calls,0);assert.equal(q.waiting,0);assert.equal(q.active,1);});
test('No wait flashing on historical queue duration',()=>{const q=run([task('connected',{lastQueue:{id:'Q',duration:123000},queueDuration:123000})],[leg()])[0];assert.equal(q.calls,0);assert.equal(q.maxWaitMs,0);});
test('Ringing offer separately counted',()=>{const q=run([task('ringing')])[0];assert.equal(q.offered,1);assert.equal(q.waiting,0);assert.equal(q.active,0);});
test('Current agent wrapup survives customer-end record',()=>{const q=run([task('ended',{isActive:false,lastActivityTime:now-500})],[],[work()])[0];assert.equal(q.wrapup,1);assert.equal(q.waiting,0);});
test('Current wrapup maps even when no today task exists',()=>assert.equal(run([],[],[work()])[0].wrapup,1));
test('Explicit later wrapup-completed clears old wrapup',()=>{const q=run([], [leg('wrapup-completed',{isActive:false,lastActivityTime:now})],[work()])[0];assert.equal(q.wrapup,0);});
test('Requeued handled contact may wait again',()=>{const q=run([task('parked',{connectedCount:1,isContactHandled:true,lastActivityTime:now})],[leg('connected')])[0];assert.equal(q.waiting,1);assert.equal(q.active,0);});
test('Transferred contact belongs only to latest queue',()=>{const q=run([task('parked',{lastQueue:{id:'R'}})],[leg()]);assert.equal(q[0].waiting,0);assert.equal(q[1].waiting,1);});
test('Completed contact not counted',()=>assert.equal(run([task('ended',{isActive:false})],[leg()])[0].waiting,0));
test('Transferred-to-DN active flag is not waiting',()=>assert.equal(run([task('transferred-to-dn')])[0].waiting,0));
test('Active and waiting different contacts counted separately',()=>{const q=run([task(),task('parked',{id:'OTHER'})])[0];assert.equal(q.active,1);assert.equal(q.waiting,1);});
test('Unknown state fails neutral',()=>assert.equal(run([task('future-state')])[0].countStatus,'unavailable'));
test('Unassigned live contact cannot create false zero',()=>assert.equal(run([task('connected',{lastQueue:null})])[0].countStatus,'unavailable'));
test('IVR outside queue not considered unassigned waiting',()=>assert.equal(run([task('ivr-connected',{lastQueue:null})])[0].waiting,0));
test('Missing queue-entry evidence does not turn historic duration into live stopwatch',()=>assert.equal(run([task('parked',{queueDuration:99000})])[0].maxWaitMs,null));
test('Verified active parked activity times current wait',()=>{const t=task('parked',{activities:{nodes:[{isActive:true,queueId:'Q',nextState:'parked',createdTime:now-8000,endedTime:-1}]}});assert.equal(run([t])[0].maxWaitMs,8000);});
test('Input failure is unavailable, never zero',()=>{const t=[];t.vbOpsUnavailable=true;assert.equal(run(t)[0].waiting,null);});
test('One task deduplicated across all three sources',()=>{const q=run([task()],[leg('connected')],[work('active')])[0];assert.equal(q.active,1);});
test('Chat and Voice queue counts use same classification',()=>{const q=ctx.vbOpsCurrentQueueRows([{id:'Q',channelType:'CHAT'}],[],[task('connected',{channelType:'chat'})],[],now)[0];assert.equal(q.waiting,0);assert.equal(q.active,1);});
test('Completed historical activity not treated current',()=>assert.equal(ctx.vbOpsCurrentActivity(slot('c','connected',{activities:{nodes:[{isCurrentActivity:true,taskId:'T',startTime:now-10000,endTime:now-5000}]}}),now),null));
