import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import vm from 'node:vm';
const code=n=>fs.readFileSync(new URL('../'+n,import.meta.url),'utf8');
const ctx=vm.createContext({buildWebexAgentRows:()=>[],buildWebexQueueRows:()=>[],getWebexDashboardSettings:async()=>({})});
vm.runInContext(code('worker-patches/agent-queue-state-r3.js'),ctx);
vm.runInContext(code('worker-patches/agent-indicators-r4.js'),ctx);
vm.runInContext(code('webex-agent-indicators.js'),ctx);
const api=ctx.VB_AGENT_INDICATORS,now=Date.now();
const session=(state='idle',name='Logged In',id='login-id',since=now-70000)=>({isActive:true,agentId:'test-agent',agentSessionId:'test-session',channelInfo:Array.from({length:6},(_,i)=>({channelId:'slot-'+i,channelType:i?'chat':'telephony',currentState:state,idleCodeName:name,lastActivityTime:since,activities:{nodes:[{isCurrentActivity:true,startTime:since,endTime:-1,state,idleCode:{id,name}}]}}))});
const metadata=s=>ctx.vbIndicatorMetadata(s,{},now);
const agent=s=>({agentId:'test-agent',sessionId:'test-session',stateIndicator:metadata(s)});
const dash={generatedAtEpoch:now,settings:{agentStateIndicators:{}}};
const live={liveStatus:'ready',liveObservedAt:now};
const noWork={active:0,wrapup:0};
const state=(a=agent(session()),p=noWork,d=dash,l=live,t=now)=>api.stateFor(a,p,d,l,t);
for(const name of ['Lunch','Meeting','Training','Coaching','Team Huddle','New custom reason'])test('Dynamic Idle reason: '+name,()=>{const m=metadata(session('idle',name,'reason-'+name));assert.equal(m.category,'idle');assert.equal(m.label,name);});
test('Six distinct channel records agree on current login reason',()=>{const m=metadata(session());assert.equal(m.idleVerified,true);assert.equal(m.idleReason.id,'login-id');assert.equal(m.stateStartedAt,now-70000);});
for(const [input,expected]of [['available','available'],['connected','engaged'],['wrapup','wrapup'],['ringing','offered']])test(input+' never inherits old Logged In reason',()=>{const m=metadata(session(input));assert.equal(m.category,expected);assert.equal(m.idleReason,null);assert.equal(state(agent(session(input))).due,false);});
test('One busy slot takes precedence over idle slots',()=>{const s=session();s.channelInfo[1].currentState='connected';assert.equal(metadata(s).category,'engaged');});
test('Unknown channel state stays neutral',()=>{assert.equal(metadata(session('unexpected-state')).category,'unknown');});
test('Missing session stays neutral',()=>assert.equal(metadata(null).category,'unknown'));
test('Grace period gates reminder',()=>{assert.equal(state().due,true);assert.equal(state(agent(session('idle','Logged In','login-id',now-59000))).due,false);});
test('Old snapshot suppresses reminder',()=>{assert.equal(state(undefined,noWork,{...dash,generatedAtEpoch:now-45001}).due,false);});
test('Current Chat workload suppresses initial login cue',()=>assert.equal(state(undefined,{active:1,wrapup:0}).due,false));
test('Newer Chat work wins over idle',()=>assert.equal(state(undefined,{active:1,wrapup:0},dash,{...live,liveObservedAt:now+1}).category,'engaged'));
test('Missing current reason ID suppresses pulse',()=>assert.equal(state(agent(session('idle','Logged In',''))).due,false));
test('Configured reason ID takes priority over name',()=>{const d={...dash,settings:{agentStateIndicators:{loginReasonId:'other'}}};assert.equal(state(undefined,noWork,d).due,false);});
const memory=()=>{const m=new Map();return{getItem:k=>m.get(k),setItem:(k,v)=>m.set(k,v)};};
test('Both views and page reload use one four-second timeline',()=>{const store=memory(),cfg=api.settings(),s=state(),first=api.makeCueStore(store);assert.equal(first.cue(s,cfg,now).pulse,true);assert.equal(first.cue(s,cfg,now+1000).elapsed,1000);assert.equal(api.makeCueStore(store).cue(s,cfg,now+4001).pulse,false);});
test('Reduced Motion suppresses and consumes animation',()=>{const a=api.makeCueStore(memory()),cfg=api.settings(),s=state();assert.equal(a.cue(s,cfg,now,true).pulse,false);assert.equal(a.cue(s,cfg,now+1000,false).pulse,false);});
test('Storage unavailable never causes perpetual pulses',()=>assert.equal(api.makeCueStore(null).cue(state(),api.settings(),now).pulse,false));
test('Reminder can be disabled without suppressing Idle color',()=>{const x=state(undefined,noWork,{...dash,settings:{agentStateIndicators:{enabled:false}}});assert.equal(x.category,'idle');assert.equal(x.login,false);});
test('Current reason transitions get distinct reminder keys',()=>assert.notEqual(state().key,state(agent(session('idle','Logged In','login-id',now-80000))).key));
for(const v of [{graceSeconds:0},{graceSeconds:'60'},{animate:'true'},{enabled:null},{other:1},{loginReasonName:''}])test('Reject invalid shared settings '+JSON.stringify(v),()=>assert.equal(ctx.vbIndicatorValidSettings(v),false));
test('Older settings clients preserve existing indicator settings',()=>{const result=ctx.vbIndicatorSettings(undefined,{enabled:false,animate:false,graceSeconds:120,loginReasonId:'known',loginReasonName:'Initial Login'});assert.equal(result.graceSeconds,120);assert.equal(result.enabled,false);assert.equal(result.loginReasonId,'known');});
test('CSS motion is finite and honors reduced motion',()=>{const css=code('webex-agent-indicators.css');assert(css.includes('2s ease-in-out 2'));assert(css.includes('prefers-reduced-motion:reduce'));assert(!css.includes('infinite'));});
function luminance(hex){const v=hex.match(/[0-9a-f]{2}/gi).map(x=>parseInt(x,16)/255).map(x=>x<=.04045?x/12.92:((x+.055)/1.055)**2.4);return .2126*v[0]+.7152*v[1]+.0722*v[2];}
for(const[b,f]of [['2ecc71','111827'],['d92d20','ffffff'],['facc15','111827'],['fb923c','111827'],['6b7280','ffffff'],['7dd3fc','111827']])test('Contrast >=4.5 '+b,()=>{const a=luminance(b),z=luminance(f);assert((Math.max(a,z)+.05)/(Math.min(a,z)+.05)>=4.5);});
test('Indicator assets load once and before integrated rendering',()=>{const h=code('webex.html');assert.equal((h.match(/src="webex-agent-indicators.js/g)||[]).length,1);assert.equal((h.match(/href="webex-agent-indicators.css/g)||[]).length,1);assert(h.indexOf('src="webex-agent-indicators.js')<h.indexOf('src="webex-integrated-chat.js'));assert(h.includes('id="agentIndicatorSettings"'));});
