import test from 'node:test';import assert from 'node:assert/strict';
import {fixture,mutation,QUEUE,MemoryStorage,ACTOR} from './fixtures.mjs';
import {defaults} from '../../callback-settings/policy.mjs';
import {nextWindow,centralDate} from '../../callback-settings/selection.mjs';
import {CallbackPlans} from '../../callback-settings/plans.mjs';
import {nativeFixture,cid,approval} from './native-fixtures.mjs';
const EP='22222222-2222-4222-8222-222222222222';
async function setup(){let reportCalls=0,empty=false;const nf=await nativeFixture();
 const f=fixture({nativeClient:nf.client,runtimeEnv:{CALLBACK_EXECUTION_CONFIG:JSON.stringify(approval())},report:()=>{reportCalls++;const now=Date.now();return {success:true,generatedAtEpoch:now,abandonedCalls:empty?[]:[{contactId:cid(1),ani:'+12025550123',startEpoch:now-50000,endEpoch:now-1000,abandonmentStage:'In queue'}]};}});
 const saved=await f.request('settings?schema=4',mutation({queueId:QUEUE,callbackEntryPointId:EP}));assert.equal(saved.http,200);
 const w=nextWindow(saved.data.state.settings,Date.now()+120000);
 const change={action:'save',mutationId:crypto.randomUUID(),expectedPlanRevision:0,selection:{scope:'selected',contactIds:[cid(1)],expectedVersion:1,date:w.date,startTime:w.startTime}};
 return {...f,change,nf,reportCalls:()=>reportCalls,empty:()=>{empty=true;}};
}
test('Disabled settings permit a persistent draft, without a native schedule, alarm or calling reservation',async()=>{const f=await setup(),r=await f.request('plans',f.change);assert.equal(r.http,200,JSON.stringify(r.data));assert.equal(r.data.plan.status,'draft');assert.equal(r.data.plan.scheduled,false);assert.equal(f.nf.client.posts,0);
 const s=[...f.stores.values()][0];assert.equal(await s.getAlarm(),null);assert.equal((await s.list({prefix:'callback:'})).size,0);
 const detail=await f.request('plans?id='+r.data.plan.id);assert.equal(detail.data.plan.rows[0].number,'+12025550123');const list=await f.request('plans');assert.equal(list.data.plans.length,1);});
test('an identical plan save is idempotent and does not re-read a vanished daily report',async()=>{const f=await setup();await f.request('plans',f.change);const before=f.reportCalls();f.empty();const second=await f.request('plans',f.change);assert.equal(second.http,200);assert.equal(second.data.replayed,true);assert.equal(f.reportCalls(),before);assert.equal(second.data.plan.revision,1);});
test('a reused plan mutation with altered time is rejected',async()=>{const f=await setup();await f.request('plans',f.change);const x=structuredClone(f.change);x.selection.startTime='09:30';const r=await f.request('plans',x);assert.equal(r.http,409);assert.equal(r.data.error,'mutation-id-reused');});
test('saved plan opens and previews from durable evidence after the original disappears from today',async()=>{const f=await setup(),p=(await f.request('plans',f.change)).data.plan;f.empty();const r=await f.request('plan-preview',{planId:p.id,expectedPlanRevision:p.revision,expectedVersion:1,date:p.window.date,startTime:p.window.startTime});assert.equal(r.http,200,JSON.stringify(r.data));assert.equal(r.data.candidates,1);assert.equal(r.data.source.kind,'saved-validated-abandonment');assert.equal(r.data.canSchedule,false);assert.equal(f.nf.client.posts,0);});
test('optimistic draft editing and archive preserve audit trail and never cancel a native call',async()=>{const f=await setup(),p=(await f.request('plans',f.change)).data.plan;
 const edit={...f.change,mutationId:crypto.randomUUID(),planId:p.id,expectedPlanRevision:1};const a=await f.request('plans',edit);assert.equal(a.http,200);assert.equal(a.data.plan.revision,2);
 const stale=await f.request('plans',{...edit,mutationId:crypto.randomUUID()});assert.equal(stale.http,409);
 const archive=await f.request('plans',{action:'archive',mutationId:crypto.randomUUID(),planId:p.id,expectedPlanRevision:2});assert.equal(archive.data.plan.status,'archived');assert.equal(f.nf.client.posts,0);
 assert.equal((await [...f.stores.values()][0].list({prefix:'plan-audit:'+p.id})).size,3);});
test('plan APIs enforce ordinary access and trusted source requirements',async()=>{const f=fixture({allowed:false});assert.equal((await f.request('plans')).http,403);assert.equal((await f.request('register')).http,403);assert.equal((await f.request('plans',{action:'archive'})).http,403);});
test('a forged source row or unsupported plan field cannot be persisted',async()=>{const f=await setup();const r=await f.request('plans',{...f.change,rows:[{number:'+12025550999'}]});assert.equal(r.http,400);assert.equal(r.data.error,'unknown-plan-field');});
test('saved plan cannot submit until all native gates and master switch pass',async()=>{const f=await setup(),p=(await f.request('plans',f.change)).data.plan;const r=await f.request('plan-schedule',{planId:p.id,expectedPlanRevision:1,expectedVersion:1,date:p.window.date,startTime:p.window.startTime,mutationId:crypto.randomUUID()});assert.equal(r.http,409);assert.equal(f.nf.client.posts,0);});
test('approved saved-plan submission atomically marks the plan and creates exactly one schedule',async()=>{const f=await setup(),p=(await f.request('plans',f.change)).data.plan;
 await f.request('settings?schema=4',mutation({enabled:true,queueId:QUEUE,callbackEntryPointId:EP},1));
 const edit={...f.change,mutationId:crypto.randomUUID(),planId:p.id,expectedPlanRevision:1,selection:{...f.change.selection,expectedVersion:2}};const updated=await f.request('plans',edit);assert.equal(updated.http,200);
 const request={planId:p.id,expectedPlanRevision:2,expectedVersion:2,date:p.window.date,startTime:p.window.startTime,mutationId:crypto.randomUUID()};
 const a=await f.request('plan-schedule',request);assert.equal(a.http,202,JSON.stringify(a.data));const replay=await f.request('plan-schedule',request);assert.equal(replay.http,202);assert.equal(replay.data.replayed,true);
 const service=f.namespace.get(f.namespace.idFromName(f.env.WEBEX_ORG_ID+':settings:v1'));await service.alarm();assert.equal(f.nf.client.posts,1);
 const stored=await f.request('plans?id='+p.id);assert.equal(stored.data.plan.status,'submitted');const register=await f.request('register');assert.equal(register.data.rows.length,1);assert.ok(register.data.rows[0].scheduleId);});
test('saved plan larger than a single storage value stores evidence in individual small records',async()=>{const storage=new MemoryStorage(),now=Date.parse('2026-10-01T13:00:00Z'),s={...defaults(),queueId:QUEUE};await storage.put('state',{version:1,settings:s});
 const plans=new CallbackPlans(storage,()=>now),w=nextWindow(s,now),rows=Array.from({length:1000},(_,i)=>({contactId:cid(i+1),number:'+1202'+String(5550000+i),disposition:'candidate'}));
 const change={action:'save',mutationId:crypto.randomUUID(),expectedPlanRevision:0,selection:{scope:'all-matching',contactIds:rows.map(r=>r.contactId),expectedVersion:1,date:w.date,startTime:w.startTime}};
 const r=await plans.save({change,preview:{rows},sourceObservedAt:now,actor:ACTOR,requestId:crypto.randomUUID()});assert.equal(r.plan.rows.length,1000);
 for(const [key,value]of storage.data)assert.ok(Buffer.byteLength(JSON.stringify(value))<128*1024,key+' exceeds durable value limit');});
test('refresh of a vanished native schedule never marks completion or releases its number',async()=>{const f=await nativeFixture();await f.engine.enqueue(f.batch());await f.engine.run();f.client.get=async()=>null;const r=await f.engine.refreshRecord(cid(1));assert.equal(r.record.nativeObservation.status,'not-in-future-inventory');assert.notEqual(r.record.status,'completed');assert.equal(f.client.posts,1);});

test('large skipped batches never exceed a durable value limit or lose skip reasons',async()=>{const f=await nativeFixture();const rows=Array.from({length:1000},(_,i)=>({contactId:cid(i+1),number:'+12025550123',disposition:i===0?'candidate':'skipped',reason:i===0?null:'same-number-already-in-batch'}));
 const result=await f.engine.enqueue(f.batch(rows));assert.equal(result.job.skipped.length,999);
 for(const [key,value]of f.storage.data)assert.ok(Buffer.byteLength(JSON.stringify(value))<128*1024,key+' exceeds value limit');
 await f.engine.run();assert.equal(f.client.posts,1);assert.equal((await f.engine.job(result.job.id)).skipped.length,999);});
test('plan pagination retains unique records and a valid cursor',async()=>{const storage=new MemoryStorage();const plans=new CallbackPlans(storage);
 for(let i=0;i<21;i++){const id=crypto.randomUUID(),at=new Date(Date.now()+i).toISOString();await storage.put('plan:'+id,{id,status:'draft',contactIds:[cid(1)],createdAt:at});await storage.put('plan-index:'+at+':'+id,id);}
 const first=await plans.list();assert.equal(first.plans.length,20);assert.ok(first.nextBefore);const second=await plans.list(first.nextBefore);assert.equal(second.plans.length,1);assert.ok(!first.plans.some(p=>p.id===second.plans[0].id));});
